//
// Created by Jerry Zhang on 2020-06-30.
//

#ifndef COMPUTERFINALPROJECT_MARCOS_H
#define COMPUTERFINALPROJECT_MARCOS_H
#define KB 1024
#define MAX_FILE_NAME_LEN 512
#define MAX_BLOCK_NUM 102400
#define BLOCK_SIZE (1 * KB)
#define MAX_CONTENT_NUM 20
#define BUFFER_SIZE 1024
#endif //COMPUTERFINALPROJECT_MARCOS_H
