//
// Created by Jerry Zhang on 2020-06-30.
//

#ifndef COMPUTERFINALPROJECT_MARCOS_H
#define COMPUTERFINALPROJECT_MARCOS_H
#define KB 1024
#define MAX_FILE_NAME_LEN 512
#define MAX_BLOCK_NUM 1024
#define BLOCK_SIZE (1 * KB)
#define SIZE_OF_FCB 1030
#define MAX_CONTENT_NUM 10
#define BUFFER_SIZE 1024
#endif //COMPUTERFINALPROJECT_MARCOS_H
